BugFix: logger info with manual field specification and automatic field numbering
ValueError: cannot switch from manual field specification to automatic field numbering